import { DOCUMENT } from '@angular/common';
import { Injectable, LOCALE_ID, inject } from '@angular/core';
import { environment } from '../../../environments/environment';

/**
 * Canonical origin used for all indexable URLs. Sourced from `environment.site.baseUrl`,
 * which is also read directly by `scripts/postbuild.mjs` (BASE_URL) — the single source
 * of truth for canonical/hreflang/sitemap/structured-data URLs.
 */
const BASE_URL = environment.site.baseUrl;

/** Input required to build a `SoftwareApplication` JSON-LD entry for a tool page. */
export interface SoftwareApplicationData {
  /** Tool title (without the ` | devTools` suffix). */
  name: string;
  /** Meta description text for the tool (same value used in menu-def.ts). */
  description: string;
  /** Router link for the page, e.g. `/json-formatter`. */
  routerLink: string;
}

/**
 * Injects/removes a `<script type="application/ld+json">` structured data tag
 * into `<head>`. Intended to be called from a page component's
 * `ngOnInit`/`ngOnDestroy` to avoid duplicating this boilerplate across every
 * tool page.
 */
@Injectable({
  providedIn: 'root',
})
export class StructuredDataService {
  private readonly document = inject(DOCUMENT);
  private readonly locale = inject(LOCALE_ID);

  private script?: HTMLScriptElement;

  /**
   * Adds a `SoftwareApplication` JSON-LD script tag for a tool page.
   * The `url` is derived from the current locale + routerLink, matching the
   * canonical URL format generated by `scripts/postbuild.mjs` (no trailing slash).
   */
  addSoftwareApplication(data: SoftwareApplicationData): void {
    const url = `${BASE_URL}/${this.locale}${data.routerLink}`;

    const script = this.document.createElement('script');
    script.type = 'application/ld+json';
    script.text = JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      'name': data.name,
      'description': data.description,
      'applicationCategory': 'DeveloperApplication',
      'operatingSystem': 'Web',
      'url': url,
      'offers': { '@type': 'Offer', 'price': '0', 'priceCurrency': 'JPY' },
    });
    this.document.head.appendChild(script);
    this.script = script;
  }

  /** Removes the previously added script tag, if any. */
  remove(): void {
    this.script?.remove();
    this.script = undefined;
  }
}
