import { DOCUMENT } from '@angular/common';
import { Injectable, LOCALE_ID, inject } from '@angular/core';
import { environment } from '../../../environments/environment';

/**
 * Canonical origin used for all indexable URLs. Sourced from `environment.site.baseUrl`,
 * which is also read directly by `scripts/postbuild.mjs` (BASE_URL) — the single source
 * of truth for canonical/hreflang/sitemap/structured-data URLs.
 */
const BASE_URL = environment.site.baseUrl;

/** Input required to build a `SoftwareApplication` JSON-LD entry for a tool page. */
export interface SoftwareApplicationData {
  /** Tool title (without the ` | devTools` suffix). */
  name: string;
  /** Meta description text for the tool (same value used in menu-def.ts). */
  description: string;
  /** Router link for the page, e.g. `/json-formatter`. */
  routerLink: string;
}

/**
 * Injects/removes `<script type="application/ld+json">` structured data tags
 * into `<head>`. Intended to be called from a page component's
 * `ngOnInit`/`ngAfterViewInit`/`ngOnDestroy` to avoid duplicating this
 * boilerplate across every tool page.
 */
@Injectable({
  providedIn: 'root',
})
export class StructuredDataService {
  private readonly document = inject(DOCUMENT);
  private readonly locale = inject(LOCALE_ID);

  /**
   * Tracks every script tag injected by this service so `remove()` can clean
   * up all of them. A single tool page can carry both a `SoftwareApplication`
   * and a `FAQPage` entry at the same time.
   */
  private readonly scripts: HTMLScriptElement[] = [];
  private breadcrumbScript?: HTMLScriptElement;

  /**
   * Adds a `SoftwareApplication` JSON-LD script tag for a tool page.
   * The `url` is derived from the current locale + routerLink, matching the
   * canonical URL format generated by `scripts/postbuild.mjs` (no trailing slash).
   */
  addSoftwareApplication(data: SoftwareApplicationData): void {
    const url = `${BASE_URL}/${this.locale}${data.routerLink}`;

    const script = this.document.createElement('script');
    script.type = 'application/ld+json';
    script.text = JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'SoftwareApplication',
      'name': data.name,
      'description': data.description,
      'applicationCategory': 'DeveloperApplication',
      'operatingSystem': 'Web',
      'url': url,
      'offers': { '@type': 'Offer', 'price': '0', 'priceCurrency': 'JPY' },
    });
    this.document.head.appendChild(script);
    this.scripts.push(script);
  }

  /**
   * Adds a `FAQPage` JSON-LD script tag by extracting question/answer pairs
   * directly from the rendered DOM (`.help-faq-item` > `.help-faq-question` /
   * `.help-faq-answer`), instead of hardcoding the FAQ text again here.
   *
   * Extracting from the DOM avoids maintaining the same Q&A content in two
   * places (the help component template and this service) and guarantees the
   * structured data always matches what is actually visible on the page —
   * including both the ja and en locales, since by the time this runs the
   * i18n text is already resolved into the DOM.
   *
   * Must be called from `ngAfterViewInit`, not `ngOnInit`: the FAQ markup
   * lives inside a child help component, which has not rendered its view yet
   * during the parent's `ngOnInit`. During SSG, Angular waits for the app to
   * become stable (including any `<head>` mutations performed here) before
   * serializing HTML, so this DOM-read-then-inject approach works safely on
   * both the server and the browser.
   */
  addFaqPageFromDom(): void {
    const items = this.document.querySelectorAll('.help-faq-item');

    const mainEntity = Array.from(items)
      .map((item) => {
        const question = item.querySelector('.help-faq-question')?.textContent?.trim() ?? '';
        const answer = item.querySelector('.help-faq-answer')?.textContent?.trim() ?? '';
        return { question, answer };
      })
      .filter(({ question, answer }) => question.length > 0 && answer.length > 0)
      .map(({ question, answer }) => ({
        '@type': 'Question',
        'name': question,
        'acceptedAnswer': { '@type': 'Answer', 'text': answer },
      }));

    if (mainEntity.length === 0) {
      return;
    }

    const script = this.document.createElement('script');
    script.type = 'application/ld+json';
    script.text = JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      'mainEntity': mainEntity,
    });
    this.document.head.appendChild(script);
    this.scripts.push(script);
  }

  /** Removes all previously added script tags, if any. */
  remove(): void {
    for (const script of this.scripts) {
      script.remove();
    }
    this.scripts.length = 0;
  }

  /**
   * Injects/replaces a `BreadcrumbList` JSON-LD script tag for the current
   * breadcrumb trail. Kept in a dedicated field so it never clobbers the
   * per-tool-page `SoftwareApplication` script managed by `addSoftwareApplication`/`remove`.
   *
   * Nodes without a `routerLink` (breadcrumb category labels, which have no
   * URL of their own) are omitted from `itemListElement` — every emitted
   * `ListItem` must have a valid `item` URL. The single-node dashboard trail
   * (Home only) is skipped entirely, since a one-item BreadcrumbList carries
   * no information.
   */
  setBreadcrumbList(items: { name: string; routerLink?: string }[]): void {
    this.breadcrumbScript?.remove();
    this.breadcrumbScript = undefined;
    if (items.length < 2) return;

    const script = this.document.createElement('script');
    script.type = 'application/ld+json';
    script.text = JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: items
        .filter((it) => it.routerLink)
        .map((it, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          name: it.name,
          // Home's routerLink is "/" — appended naively that would double up
          // into a trailing slash ("/ja/"), the exact issue fixed for the
          // home link elsewhere (see HomeLinkDirective / issue #204).
          item: `${BASE_URL}/${this.locale}${it.routerLink === '/' ? '' : it.routerLink}`,
        })),
    });
    this.document.head.appendChild(script);
    this.breadcrumbScript = script;
  }
}
