import { Locale } from "../../../app/components/locale/locale-model";
import { Text } from "../text";

export const DEF_TEXT: { [locale in Locale]: Text } = {
  ja: {
    // common
    'appTitle': 'devTools',
    'ja': '日本語',
    'en': 'English',
    'guest': 'ゲスト',
    'goBackHome': 'ホームに戻る',
    'copyRight': '© 2024 Yutaka Morihara',
    'hours': '時',
    'minutes': '分',
    'seconds': '秒',
    'ok': 'はい',
    'cancel': 'キャンセル',
    'reload': '更新',
    'copyToClipboard': 'クリップボードにコピーする',
    'copiedMessage': 'コピーしました。',
    // error
    '404ErrorPage': 'ページが見つかりません',
    'notFoundErrorTitle': 'ページが見つかりません',
    'notFoundErrorMessage': '申し訳ございません。\nお探しのページは、移動または削除された可能性があります。',
    // dashboard
    'dashboardPage': 'ダッシュボード | devTools',
    'dashboardMenu': 'ダッシュボード',
    'usageCardTitle': 'ご利用方法',
    'usageCardDescription': '開発者のためのシンプルなユーティリティ集です。\n\n各ツールを選択してご利用ください。\nデータは一切保存されないので、安心してご利用ください。',
    'menuCardTitle': 'メニュー',
    'releaseCardTitle': 'リリース情報',
    'githubCardTitle': '問い合わせ',
    'githubCardDescription': 'このツールはオープンソースです。\n不具合や要望などがありましたら、GitHubのIssueにてお知らせください。',
    'githubCardLinkText': 'GitHub Issuesに移動',
    'updateHistoryCardTitle': '更新履歴',
    // ulid gen
    'ulidGenPage': 'ULID生成 | devTools',
    'ulidGenMenu': 'ULID生成',
    'ulidGenTitle': 'ULID生成ツール',
    'ulidGenInputHeading': '生成条件',
    'ulidGenOutputHeading': '生成結果',
    'baseTimestamp': '基準日時(タイムスタンプ)',
    'baseDate': '基準日',
    'isMonoIncreaseMode': '単調増加',
    'isMonoIncreaseModeHint': 'ULID後部のランダム部分を1ビットずつの増分で生成します。',
    'generate': '生成',
    'generatingSize': '生成数',
    'generatingSizePlaceholder': '最大1,000',
    'ulidGenInputErrorRequired': '必須項目を入力してください。',
    'ulidGenInputErrorGeneratingSizeRange': '生成数は1以上1,000以下で入力してください。',
    'ulidGenInputErrorBaseTimestampMin': '基準日時は0以上で入力してください。',
    'datetimeMakerDialogTitle': '基準日時の選択',
    'datetimeMakerDialogMessage': '基準日時を入力してください。\n選択された日時はタイムスタンプへと変換されます。',
    'datetimeMakerDialogErrorRequired': '必須項目です。',
    'datetimeMakerDialogErrorInvalidBaseDate': '正しい基準日を入力してください。例: {0}',
    'datetimeMakerDialogErrorInvalidTime': '正しい時間を入力してください。',
    'selectDatetime': '日時を選択',
    // uuid gen
    'uuidGenPage': 'UUID生成 | devTools',
    'uuidGenMenu': 'UUID生成',
    'uuidGenTitle': 'UUID生成ツール',
    'uuidGenInputHeading': '生成条件',
    'uuidGenOutputHeading': '生成結果',
    'uuidGenHint': 'UUIDは、Universally Unique Identifierの略で、世界中で一意な識別子を生成するための標準です。',
    'uuidVersion': 'バージョン',
    'uuidVersionHint': 'v1: 時刻とMACアドレスを組み合わせて生成。時系列順に並びやすいが生成元が推測されやすい。\nv4: ほぼ完全にランダムに生成。衝突確率が極めて低く最も広く使われている。\nv7: Unix時間と乱数を組み合わせて生成。時系列順に並べやすくかつプライバシーに配慮されている。',
    'uuidGenInputErrorGeneratingSizeRequired': '生成数を入力してください。',
    'uuidGenInputErrorGeneratingSizeRange': '生成数は1以上1,000以下で入力してください。',
  },
  en: {
    // common
    'appTitle': 'devTools',
    'ja': '日本語',
    'en': 'English',
    'guest': 'Guest',
    'goBackHome': 'Back to Home',
    'copyRight': '© 2024 Yutaka Morihara',
    'hours': 'Hours',
    'minutes': 'Minutes',
    'seconds': 'Seconds',
    'ok': 'Ok',
    'cancel': 'Cancel',
    'reload': 'Reload',
    'copyToClipboard': 'Copy to Clipboard',
    'copiedMessage': 'Copied!',
    // error
    'notFoundErrorTitle': 'Page not found',
    'notFoundErrorMessage': 'Sorry, the page you\'re looking for can\'t be found.',
    // dashboard
    'dashboardPage': 'Dashboard | devTools',
    'usageCardTitle': 'How to Use',
    'usageCardDescription': 'This is a simple utility collection for developers.\n\nPlease select a tool to use.\nNo data is saved, so you can use it with confidence.',
    'menuCardTitle': 'Menu',
    'releaseCardTitle': 'Release Information',
    'githubCardTitle': 'Contact',
    'githubCardDescription': 'This tool is open source.\nIf you have any bugs or requests, please let us know on GitHub Issues.',
    'githubCardLinkText': 'Go to GitHub Issues',
    'updateHistoryCardTitle': 'Update History',
    // ulid gen
    'ulidGenPage': 'ULID Generator | devTools',
    'ulidGenMenu': 'ULID Generator',
    'ulidGenTitle': 'ULID Generating Tool',
    'ulidGenInputHeading': 'Conditions',
    'ulidGenOutputHeading': 'Results',
    'baseTimestamp': 'Base datetime - Timestamp',
    'baseDate': 'Base date',
    'isMonoIncreaseMode': 'Increase monotonically',
    'isMonoIncreaseModeHint': 'The random part at the end of the ULID is generated in increments of 1 bit.',
    'generate': 'Generate',
    'generatingSize': 'Number of ULIDs',
    'generatingSizePlaceholder': 'Max 1,000',
    'ulidGenInputErrorRequired': 'Required fields are missing.',
    'ulidGenInputErrorGeneratingSizeRange': 'The number of ULIDs to generate must be between 1 and 1,000.',
    'ulidGenInputErrorBaseTimestampMin': 'The base datetime must be greater than or equal to 0.',
    'datetimeMakerDialogTitle': 'Select Base Datatime',
    'datetimeMakerDialogMessage': 'Please enter the base datetime.\nThe selected datetime will be converted to a timestamp.',
    'datetimeMakerDialogErrorRequired': 'Required fields are missing.',
    'datetimeMakerDialogErrorInvalidBaseDate': 'Invalid base date. ex) {0}',
    'datetimeMakerDialogErrorInvalidTime': 'Invalid time.',
    'selectDatetime': 'Select datetime',
    // uuid gen
    'uuidGenPage': 'UUID Generator | devTools',
    'uuidGenMenu': 'UUID Generator',
    'uuidGenTitle': 'UUID Generating Tool',
    'uuidGenInputHeading': 'Conditions',
    'uuidGenOutputHeading': 'Results',
    'uuidGenHint': 'UUID stands for Universally Unique Identifier, a standard for generating unique identifiers worldwide.',
    'uuidVersion': 'Version',
    'uuidVersionHint': 'v1: Combines time and MAC address for generation. Easier to sort chronologically but more susceptible to source inference.\nv4: Generates almost completely randomly. Extremely low collision probability and most widely used.\nv7: Combines Unix time and random numbers for generation. Easier to sort chronologically while considering privacy.',
    'uuidGenInputErrorGeneratingSizeRequired': 'Please enter the number of UUIDs to generate.',
    'uuidGenInputErrorGeneratingSizeRange': 'The number of UUIDs to generate must be between 1 and 1,000.',
  }
}
