import { Locale, Text } from "../text";

export const DEF_TEXT: { [locale in Locale]: Text } = {
  ja: {
    // common
    'guest': 'ゲスト',
    'goBackHome': 'ホームに戻る',
    'copyRight': '© 2024 Yutaka Morihara',
    'hours': '時',
    'minutes': '分',
    'seconds': '秒',
    'ok': 'はい',
    'cancel': 'キャンセル',
    'reload': '更新',
    'copyToClipboard': 'クリップボードにコピーする',
    'copiedMessage': 'コピーしました。',
    // error
    '404ErrorPage': 'ページが見つかりません',
    'notFoundErrorTitle': 'ページが見つかりません',
    'notFoundErrorMessage': '申し訳ございません。\nお探しのページは、移動または削除された可能性があります。',
    // ulid gen
    'ulidGenPage': 'ULID生成',
    'ulidGenTitle': 'ULID生成ツール',
    'ulidGenInputHeading': 'ULID生成条件',
    'ulidGenOutputHeading': '生成結果',
    'baseTimestamp': '基準日時(タイムスタンプ)',
    'baseDate': '基準日',
    'isMonoIncreaseMode': '単調増加',
    'isMonoIncreaseModeHint': 'ULID後部のランダム部分を1ビットずつの増分で生成します。',
    'generate': '生成',
    'generatingSize': '生成数',
    'generatingSizePlaceholder': '最大5,000',
    'ulidGenInputErrorRequired': '必須項目を入力してください。',
    'ulidGenInputErrorGeneratingSizeRange': '生成数は1以上5,000以下で入力してください。',
    'ulidGenInputErrorBaseTimestampMin': '基準日時は0以上で入力してください。',
    'datetimeMakerDialogTitle': '基準日時の選択',
    'datetimeMakerDialogMessage': '基準日時を入力してください。\n選択された日時はタイムスタンプへと変換されます。',
    'datetimeMakerDialogErrorRequired': '必須項目です。',
    'datetimeMakerDialogErrorInvalidBaseDate': '正しい基準日を入力してください。例: {0}',
    'datetimeMakerDialogErrorInvalidTime': '正しい時間を入力してください。',
    'selectDatetime': '日時を選択',
  },
  en: {
    // common
    'guest': 'Guest',
    'goBackHome': 'Back to Home',
    'copyRight': '© 2024 Yutaka Morihara',
    'hours': 'Hours',
    'minutes': 'Minutes',
    'seconds': 'Seconds',
    'ok': 'Ok',
    'cancel': 'Cancel',
    'reload': 'Reload',
    'copyToClipboard': 'Copy to Clipboard',
    'copiedMessage': 'Copied!',
    // error
    'notFoundErrorTitle': 'Page not found',
    'notFoundErrorMessage': 'Sorry, the page you\'re looking for can\'t be found.',
    // ulid gen
    'ulidGenTitle': 'ULID Generator',
    'ulidGenInputHeading': 'Conditions',
    'ulidGenOutputHeading': 'Results',
    'baseTimestamp': 'Base datetime - Timestamp',
    'baseDate': 'Base date',
    'isMonoIncreaseMode': 'Increase monotonically',
    'isMonoIncreaseModeHint': 'The random part at the end of the ULID is generated in increments of 1 bit.',
    'generate': 'Generate',
    'generatingSize': 'Number of ULIDs to generate',
    'generatingSizePlaceholder': 'Max 5,000',
    'ulidGenInputErrorRequired': 'Required fields are missing.',
    'ulidGenInputErrorGeneratingSizeRange': 'The number of ULIDs to generate must be between 1 and 5,000.',
    'ulidGenInputErrorBaseTimestampMin': 'The base datetime must be greater than or equal to 0.',
    'datetimeMakerDialogTitle': 'Select Base Datatime',
    'datetimeMakerDialogMessage': 'Please enter the base datetime.\nThe selected datetime will be converted to a timestamp.',
    'datetimeMakerDialogErrorRequired': 'Required fields are missing.',
    'datetimeMakerDialogErrorInvalidBaseDate': 'Invalid base date. ex) {0}',
    'datetimeMakerDialogErrorInvalidTime': 'Invalid time.',
    'selectDatetime': 'Select datetime',
  }
}
