import { Component, computed, inject, LOCALE_ID } from '@angular/core';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { ApplicationPageTemplateComponent } from '../../../components/application-page-template/application-page-template.component';
import { HeadingComponent } from '../../../components/heading/heading.component';
import { ArticleRelatedToolsComponent } from '../../../components/article-related-tools/article-related-tools.component';
import contentJa from '../../../../generated/articles/articles-content.ja.json';
import contentEn from '../../../../generated/articles/articles-content.en.json';
import { ArticleListItem, getArticlesList } from '../articles-list';

/** slug → { html } generated by scripts/prebuild-articles.mjs at build time. */
type ArticlesContent = Record<string, { html: string }>;

const CONTENT_BY_LOCALE: Record<string, ArticlesContent> = {
  ja: contentJa,
  en: contentEn,
};

/**
 * Generic article detail page shared by every article. Renders the
 * build-time generated, sanitized HTML fragment for the current locale via
 * `[innerHTML]`, alongside the common chrome (heading, published date,
 * related tools). Metadata (title/summary/relatedTools) is sourced from the
 * build-time generated article list (Markdown frontmatter), not from a
 * hand-maintained TypeScript definition file.
 *
 * The route registering this component must supply the article's `slug`
 * via route `data` (see `articles-page.routes.ts`).
 */
@Component({
  selector: 'app-article-detail',
  imports: [
    RouterModule,
    MatButtonModule,
    MatCardModule,
    MatIconModule,
    ApplicationPageTemplateComponent,
    HeadingComponent,
    ArticleRelatedToolsComponent,
  ],
  templateUrl: './article-detail.component.html',
  styleUrl: './article-detail.component.scss',
})
export class ArticleDetailComponent {
  private readonly route = inject(ActivatedRoute);
  private readonly locale = inject(LOCALE_ID);

  private readonly slug = this.route.snapshot.data['slug'] as string;

  readonly article = computed<ArticleListItem | undefined>(() =>
    getArticlesList(this.locale).find((item) => item.slug === this.slug),
  );

  readonly html = computed<string>(() => {
    const content = CONTENT_BY_LOCALE[this.locale] ?? CONTENT_BY_LOCALE['ja'];
    return content[this.slug]?.html ?? '';
  });
}
