import { Component, computed, inject, LOCALE_ID } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ApplicationPageTemplateComponent } from '../../../components/application-page-template/application-page-template.component';
import { HeadingComponent } from '../../../components/heading/heading.component';
import { HyperLinkTextComponent } from '../../../components/hyper-link-text/hyper-link-text.component';
import { ArticleRelatedToolsComponent } from '../../../components/article-related-tools/article-related-tools.component';
import { ARTICLES, ArticleItem } from '../../../../resources/articles/def/articles-def';
import contentJa from '../../../../generated/articles/articles-content.ja.json';
import contentEn from '../../../../generated/articles/articles-content.en.json';

/** slug → { html } generated by scripts/prebuild-articles.mjs at build time. */
type ArticlesContent = Record<string, { html: string }>;

const CONTENT_BY_LOCALE: Record<string, ArticlesContent> = {
  ja: contentJa,
  en: contentEn,
};

/**
 * Generic article detail page for Markdown-sourced articles
 * (`ArticleItem.bodySource === 'markdown'`). Renders the build-time
 * generated, sanitized HTML fragment for the current locale via
 * `[innerHTML]`, alongside the same chrome (heading, published date,
 * related tools) used by the hand-written article components so the two
 * can coexist during the migration.
 *
 * The route registering this component must supply the article's `slug`
 * via route `data` (see `articles-page.routes.ts`).
 */
@Component({
  selector: 'app-article-detail',
  imports: [
    ApplicationPageTemplateComponent,
    HeadingComponent,
    HyperLinkTextComponent,
    ArticleRelatedToolsComponent,
  ],
  templateUrl: './article-detail.component.html',
  styleUrl: './article-detail.component.scss',
})
export class ArticleDetailComponent {
  private readonly route = inject(ActivatedRoute);
  private readonly locale = inject(LOCALE_ID);

  private readonly slug = this.route.snapshot.data['slug'] as string;

  readonly article = computed<ArticleItem | undefined>(() =>
    ARTICLES.find((item) => item.routerLink === `/articles/${this.slug}`),
  );

  readonly html = computed<string>(() => {
    const content = CONTENT_BY_LOCALE[this.locale] ?? CONTENT_BY_LOCALE['ja'];
    return content[this.slug]?.html ?? '';
  });
}
