name: PR Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check-i18n:
    if: "! github.event.pull_request.draft"
    uses: ./.github/workflows/reusable/check-i18n.yml
    permissions:
      contents: read

  auto-approve:
    needs: check-i18n
    if: "! github.event.pull_request.draft"
    uses: ./.github/workflows/reusable/auto-approve.yml
    permissions:
      pull-requests: write
    secrets: inherit
